"""Database tables (SQLAlchemy ORM models)."""

from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, index=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    # One-to-one: each user has exactly one preferences row, created after signup.
    preferences: Mapped["UserPreference | None"] = relationship(
        back_populates="user", uselist=False, cascade="all, delete-orphan"
    )
    ingredients: Mapped[list["Ingredient"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    recipes: Mapped[list["Recipe"]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class UserPreference(Base):
    """Answers to the onboarding questionnaire (also editable later in Settings)."""

    __tablename__ = "user_preferences"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), unique=True)

    is_vegetarian: Mapped[bool] = mapped_column(Boolean, default=False)
    is_vegan: Mapped[bool] = mapped_column(Boolean, default=False)
    allergies: Mapped[list] = mapped_column(JSON, default=list)
    follows_diet: Mapped[bool] = mapped_column(Boolean, default=False)
    diet_type: Mapped[str] = mapped_column(String(100), default="")
    diet_purpose: Mapped[str] = mapped_column(String(255), default="")
    disliked_foods: Mapped[list] = mapped_column(JSON, default=list)
    preferred_difficulty: Mapped[str] = mapped_column(String(20), default="easy")
    preferred_prep_time: Mapped[str] = mapped_column(String(20), default="15_30")

    user: Mapped["User"] = relationship(back_populates="preferences")


class Ingredient(Base):
    """A single ingredient the user currently has, with a quantity."""

    __tablename__ = "ingredients"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    name: Mapped[str] = mapped_column(String(100))
    quantity: Mapped[float] = mapped_column(Float, default=1)
    unit: Mapped[str] = mapped_column(String(20), default="pcs")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    user: Mapped["User"] = relationship(back_populates="ingredients")


class Recipe(Base):
    """A recipe generated by OpenAI. Every generated recipe is stored here:
    the History tab lists all of them, the Recipes tab filters to favorites.
    """

    __tablename__ = "recipes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    meal_type: Mapped[str] = mapped_column(String(50))
    title: Mapped[str] = mapped_column(String(200))
    # Free-form recipe body (prep_time, difficulty, ingredients_used, steps).
    content: Mapped[dict] = mapped_column(JSON)
    is_favorite: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    user: Mapped["User"] = relationship(back_populates="recipes")
